function passengerHome(){
 return `<div class="screen"><header class="hero-header"><div class="brand-row"><div class="brand-mark">R</div><span>Raahi</span>${pill('UI V0.1')}</div><div class="row between greeting"><div><small>Good evening</small><h1>Where are you going?</h1></div>${avatar('Priya','small')}</div></header><div class="content-stack overlap">
 <div class="market-strip feature-card"><div><small>Operating market</small><strong>${state.market}</strong></div><select id="market">${['Gomoh','Dhanbad'].map(m=>`<option ${m===state.market?'selected':''}>${m}</option>`).join('')}</select></div>
 <div class="location-card feature-card"><div class="route-visual"><span class="route-dot green"></span><span class="vertical-line"></span><span class="route-dot dark"></span></div><label><small>Your current location</small><select id="from">${locationOptions(state.from)}</select></label><label><small>Destination</small><select id="to">${locationOptions(state.to)}</select></label><button class="locate" data-action="live-location">⌖ Use my live location</button></div>
 ${section('Choose your ride','Same quote process for ToTo and Car')}
 <div class="ride-grid"><button class="ride-option ${state.vehicle==='toto'?'selected':''}" data-vehicle="toto"><span class="icon">🛺</span><strong>ToTo</strong><small>Local & affordable</small>${state.vehicle==='toto'?'<span class="selected-check">✓</span>':''}</button><button class="ride-option ${state.vehicle==='car'?'selected':''}" data-vehicle="car"><span class="icon">🚗</span><strong>Car</strong><small>Choose capacity</small>${state.vehicle==='car'?'<span class="selected-check">✓</span>':''}</button></div>
 ${state.vehicle==='car'?`<div class="feature-card capacity-card"><small>Car seating capacity</small><div class="segmented">${[4,5,6,7].map(n=>`<button data-seats="${n}" class="${state.seats===n?'active':''}">${n} seats</button>`).join('')}</div></div>`:''}
 <div class="feature-card offer-card"><div><small>Your proposed fare</small><h2>₹${state.offer}</h2><p>Nearby drivers can accept or send their own quote.</p></div><div class="fare-controls"><button data-fare="-10">−</button><button data-fare="10">+</button></div></div>
 <div class="admin-rule-note"><span>ⓘ</span><p><strong>${state.market} payment:</strong> ${state.payment[state.market]==='driver'?'Passenger pays the driver directly.':'Passenger pays Raahi.'}</p></div>
 <button class="primary full big" data-action="request-quotes" ${state.from===state.to?'disabled':''}>${state.from===state.to?'Choose a different destination':'Request driver quotes'}</button><p class="fineprint">No payment is taken until you choose a driver.</p></div></div>`;
}

function passengerQuotes(){
 const eligible = drivers.filter(isDriverEligible);
 return `<div class="screen"><header class="app-header compact"><button class="ghost-icon" data-action="passenger-home">←</button><div><strong>Driver quotes</strong><small>${rideLabel()} • your offer ₹${state.offer}</small></div><span class="pulse-dot"></span></header><div class="content-stack">${routeCard()}<div class="waiting-banner"><span class="spinner"></span><div><strong>Request sent to nearby drivers</strong><small>Quotes appear here as drivers respond.</small></div></div>${section('Responses',eligible.length+' eligible demo drivers')}${eligible.map((d,i)=>{const r=replyFor(d,i);const status=r.status;const amount=r.amount; return `<div class="quote-card ${status==='pending'?'pending':''}">${avatar(d.name)}<div class="quote-main"><div class="row between"><div><h3>${d.name}</h3><p>${d.vehicle} • ⭐ ${d.rating}</p></div>${status==='accepted'?pill('Accepted ₹'+amount,'good'):status==='counter'?pill('Counterquote','warn'):pill('Waiting')}</div><div class="quote-bottom"><span>${d.distance}</span><strong>${amount?'₹'+amount:'—'}</strong></div>${status!=='pending'?`<button class="primary full" data-choose="${d.name}" data-amount="${amount}">Choose ${d.name.split(' ')[0]}</button>`:''}</div></div>`}).join('')}</div></div>`;
}

function passengerBooked(){
 const d=state.chosen;
 return `<div class="screen"><header class="app-header compact"><button class="ghost-icon" data-action="back-quotes">←</button><div><strong>Ride confirmed</strong><small>Driver is on the way</small></div>${pill('Confirmed','good')}</header>${mapPreview()}<div class="content-stack"><div class="success-card"><div class="success-mark">✓</div><div><h2>${d.name}</h2><p>${d.vehicle} • ⭐ ${d.rating}</p></div><strong>₹${d.amount}</strong></div><div class="feature-card"><div class="route-line"><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="route-stem"></div><div class="route-line"><span class="route-dot dark"></span><div><small>Destination</small><strong>${state.to}</strong></div></div></div><div class="feature-card payment-card"><div class="row between"><div><small>Payment configured by ${state.market} admin</small><h3>${state.payment[state.market]==='driver'?'Pay driver directly':'Pay Raahi'}</h3></div>${pill(state.payment[state.market]==='driver'?'Direct':'Raahi',state.payment[state.market]==='driver'?'warn':'blue')}</div><p>${state.payment[state.market]==='driver'?'Pay the driver after the ride. The driver confirms payment received in their app.':'Payment is collected by Raahi. Driver settlement happens separately.'}</p><button class="${state.payment[state.market]==='driver'?'secondary':'primary'} full">${state.payment[state.market]==='driver'?'Payment will be made to driver':'Pay ₹'+d.amount+' to Raahi'}</button></div><button class="text-button" data-action="new-ride">Book another ride</button></div></div>`;
}
function passenger(){return state.passengerStep==='home'?passengerHome():state.passengerStep==='quotes'?passengerQuotes():passengerBooked()}

