function passengerHome(){
 const rule=totoFareRule();
 const fixed=isFixedTotoFare();
 const fareCard=fixed
   ? `<div class="feature-card offer-card fixed-fare-card"><div><small>Fixed ToTo fare • ${rule.distance} km</small><h2>₹${rule.amount}</h2><p>Set by ${state.market} admin for the ${rule.label} distance slab. No fare negotiation on this ride.</p></div>${pill('Fixed fare','good')}</div>`
   : `<div class="feature-card offer-card"><div><small>${state.vehicle==='toto'?'Your proposed fare • '+rule.distance+' km':'Your proposed fare'}</small><h2>₹${state.offer}</h2><p>Nearby drivers can accept or send their own quote.</p></div><div class="fare-controls"><button data-fare="-10">−</button><button data-fare="10">+</button></div></div>`;
 const actionLabel=fixed?'Find ToTo drivers':'Request driver quotes';
 return `<div class="screen"><header class="hero-header"><div class="brand-row"><div class="brand-mark">R</div><span>Raahi</span>${pill('UI V0.1')}</div><div class="row between greeting"><div><small>Good evening</small><h1>Where are you going?</h1></div>${avatar('Priya','small')}</div></header><div class="content-stack overlap">
 <div class="market-strip feature-card"><div><small>Operating market</small><strong>${state.market}</strong></div><select id="market">${['Gomoh','Dhanbad'].map(m=>`<option ${m===state.market?'selected':''}>${m}</option>`).join('')}</select></div>
 <div class="location-card feature-card"><div class="route-visual"><span class="route-dot green"></span><span class="vertical-line"></span><span class="route-dot dark"></span></div><label><small>Your current location</small><select id="from">${locationOptions(state.from)}</select></label><label><small>Destination</small><select id="to">${locationOptions(state.to)}</select></label><button class="locate" data-action="live-location">⌖ Use my live location</button></div>
 <div class="distance-chip">📍 Demo route distance: <strong>${routeDistanceKm()} km</strong></div>
 ${section('Choose your ride',state.vehicle==='toto'?'ToTo fare follows local distance rules':'Car continues with driver quotation')}
 <div class="ride-grid"><button class="ride-option ${state.vehicle==='toto'?'selected':''}" data-vehicle="toto"><span class="icon">🛺</span><strong>ToTo</strong><small>Local distance pricing</small>${state.vehicle==='toto'?'<span class="selected-check">✓</span>':''}</button><button class="ride-option ${state.vehicle==='car'?'selected':''}" data-vehicle="car"><span class="icon">🚗</span><strong>Car</strong><small>Choose capacity</small>${state.vehicle==='car'?'<span class="selected-check">✓</span>':''}</button></div>
 ${state.vehicle==='car'?`<div class="feature-card capacity-card"><small>Car seating capacity</small><div class="segmented">${[4,5,6,7].map(n=>`<button data-seats="${n}" class="${state.seats===n?'active':''}">${n} seats</button>`).join('')}</div></div>`:''}
 ${fareCard}
 ${state.vehicle==='toto'?`<div class="admin-rule-note"><span>ⓘ</span><p><strong>${state.market} ToTo rule:</strong> ${fixed?`${rule.label} = fixed ₹${rule.amount}.`:`${rule.label} = driver negotiation.`}</p></div>`:''}
 <div class="admin-rule-note"><span>ⓘ</span><p><strong>${state.market} payment:</strong> ${state.payment[state.market]==='driver'?'Passenger pays the driver directly.':'Passenger pays Raahi.'}</p></div>
 <button class="primary full big" data-action="request-quotes" ${state.from===state.to?'disabled':''}>${state.from===state.to?'Choose a different destination':actionLabel}</button><p class="fineprint">${fixed?'The admin-set fare is the same for every eligible ToTo driver.':'No payment is taken until you choose a driver.'}</p></div></div>`;
}

function passengerQuotes(){
 const eligible = drivers.filter(isDriverEligible);
 const fixed=isFixedTotoFare();
 const fare=currentFare();
 return `<div class="screen"><header class="app-header compact"><button class="ghost-icon" data-action="passenger-home">←</button><div><strong>${fixed?'Choose a ToTo driver':'Driver quotes'}</strong><small>${rideLabel()} • ${fixed?'fixed fare':'your offer'} ₹${fare}</small></div><span class="pulse-dot"></span></header><div class="content-stack">${routeCard()}<div class="waiting-banner"><span class="spinner"></span><div><strong>${fixed?'Request sent at the fixed local fare':'Request sent to nearby drivers'}</strong><small>${fixed?'Drivers can accept or pass. They cannot change this fare.':'Quotes appear here as drivers respond.'}</small></div></div>${section('Responses',eligible.length+' eligible demo drivers')}${eligible.map((d,i)=>{const r=replyFor(d,i);const status=r.status;const amount=r.amount; return `<div class="quote-card ${status==='pending'?'pending':''}">${avatar(d.name)}<div class="quote-main"><div class="row between"><div><h3>${d.name}</h3><p>${d.vehicle} • ⭐ ${d.rating}</p></div>${status==='accepted'?pill((fixed?'Accepted fixed ₹':'Accepted ₹')+amount,'good'):status==='counter'?pill('Counterquote','warn'):pill('Waiting')}</div><div class="quote-bottom"><span>${d.distance}</span><strong>${amount?'₹'+amount:'—'}</strong></div>${status!=='pending'?`<button class="primary full" data-choose="${d.name}" data-amount="${amount}">Choose ${d.name.split(' ')[0]}</button>`:''}</div></div>`}).join('')}</div></div>`;
}

function passengerBooked(){
 const d=state.chosen;
 return `<div class="screen"><header class="app-header compact"><button class="ghost-icon" data-action="back-quotes">←</button><div><strong>Ride confirmed</strong><small>Driver is on the way</small></div>${pill('Confirmed','good')}</header>${mapPreview()}<div class="content-stack"><div class="success-card"><div class="success-mark">✓</div><div><h2>${d.name}</h2><p>${d.vehicle} • ⭐ ${d.rating}</p></div><strong>₹${d.amount}</strong></div><div class="feature-card"><div class="route-line"><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="route-stem"></div><div class="route-line"><span class="route-dot dark"></span><div><small>Destination</small><strong>${state.to}</strong></div></div></div>${state.vehicle==='toto'?`<div class="feature-card"><div class="row between"><div><small>ToTo fare policy</small><h3>${isFixedTotoFare()?'Fixed local fare':'Negotiated fare'}</h3></div>${pill(routeDistanceKm()+' km','blue')}</div><p>${isFixedTotoFare()?`${state.market} admin fixed this distance slab at ₹${d.amount}.`:'This route is beyond the local fixed-fare slabs, so the fare was negotiated.'}</p></div>`:''}<div class="feature-card payment-card"><div class="row between"><div><small>Payment configured by ${state.market} admin</small><h3>${state.payment[state.market]==='driver'?'Pay driver directly':'Pay Raahi'}</h3></div>${pill(state.payment[state.market]==='driver'?'Direct':'Raahi',state.payment[state.market]==='driver'?'warn':'blue')}</div><p>${state.payment[state.market]==='driver'?'Pay the driver after the ride. The driver confirms payment received in their app.':'Payment is collected by Raahi. Driver settlement happens separately.'}</p><button class="${state.payment[state.market]==='driver'?'secondary':'primary'} full">${state.payment[state.market]==='driver'?'Payment will be made to driver':'Pay ₹'+d.amount+' to Raahi'}</button></div><button class="text-button" data-action="new-ride">Book another ride</button></div></div>`;
}
function passenger(){return state.passengerStep==='home'?passengerHome():state.passengerStep==='quotes'?passengerQuotes():passengerBooked()}

