function driverRequestCard(d){
 const e=state.engagement;
 const rideAssigned=state.ride?.name===d.name;
 if(rideAssigned){
   return `<div class="assigned-banner"><small>RIDE CONFIRMED</small><h3>You are matched with Priya</h3><p>${state.from} → ${state.to} • Fare ₹${state.ride.amount}</p></div>`;
 }
 if(!e || e.driverName!==d.name){
   return `<div class="empty-state"><span>◌</span><h2>No request for you right now</h2><p>You remain available in the driver pool. Raahi engages only one driver with a passenger at a time.</p></div>`;
 }
 const fixed=isFixedTotoFare();
 const fare=e.amount;
 if(e.status==='counter'){
   return `<div class="request-card"><div class="request-top"><div><small>YOUR COUNTER</small><h1>₹${e.counter}</h1></div>${pill('Waiting for Priya','warn')}</div><div class="route-summary"><div><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="stem"></div><div><span class="route-dot dark"></span><div><small>Drop</small><strong>${state.to}</strong></div></div></div><div class="accepted-box"><span>✓</span><div><strong>Counter sent</strong><small>Priya can accept or decline. No further counter round.</small></div></div></div>`;
 }
 if(e.status==='draft-counter' && !fixed){
   return `<div class="request-card"><div class="request-top"><div><small>PRIYA'S OFFER</small><h1>₹${fare}</h1></div><div class="countdown">24s</div></div><div class="route-summary"><div><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="stem"></div><div><span class="route-dot dark"></span><div><small>Drop</small><strong>${state.to}</strong></div></div></div><div class="request-meta"><span>${d.type==='toto'?'🛺':'🚗'} ${rideLabel()}</span><span>👤 Priya</span><span>📍 ${d.distance.replace(' away','')} pickup</span></div><div class="counter-box"><small>Your one counter</small><div><button data-counter="-10">−</button><strong>₹${state.counterDraft}</strong><button data-counter="10">+</button></div><button class="primary full" data-action="send-counter">Send ₹${state.counterDraft} counter</button><button class="text-button" data-action="driver-pass">Pass this request</button></div></div>`;
 }
 if(fixed){
   const rule=totoFareRule();
   return `<div class="request-card"><div class="request-top"><div><small>FIXED LOCAL FARE</small><h1>₹${fare}</h1></div>${pill(rule.distance+' km','blue')}</div><div class="route-summary"><div><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="stem"></div><div><span class="route-dot dark"></span><div><small>Drop</small><strong>${state.to}</strong></div></div></div><div class="request-meta"><span>🛺 ToTo</span><span>👤 Priya</span><span>📍 ${d.distance.replace(' away','')} pickup</span></div><div class="fixed-driver-rule"><strong>${e.market} fixed this fare.</strong><small>You can Accept or Pass. Counterquotes are disabled.</small></div><div class="two-buttons"><button class="secondary" data-action="driver-pass">Pass</button><button class="primary" data-action="accept-driver">Accept ₹${fare}</button></div></div>`;
 }
 return `<div class="request-card"><div class="request-top"><div><small>PRIYA'S OFFER</small><h1>₹${fare}</h1></div><div class="countdown">24s</div></div><div class="route-summary"><div><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="stem"></div><div><span class="route-dot dark"></span><div><small>Drop</small><strong>${state.to}</strong></div></div></div><div class="request-meta"><span>${d.type==='toto'?'🛺':'🚗'} ${rideLabel()}</span><span>👤 Priya</span><span>📍 ${d.distance.replace(' away','')} pickup</span></div><div class="two-buttons"><button class="secondary" data-action="counter-mode">Counter once</button><button class="primary" data-action="accept-driver">Accept ₹${fare}</button></div><button class="text-button" data-action="driver-pass">Pass this request</button></div>`;
}

function driverPaymentCard(d){
 if(state.ride?.name!==d.name) return '';
 const market=state.ride.market;
 const direct=state.payment[market]==='driver';
 if(direct){
   const confirmed=Boolean(state.paymentConfirmed[d.name]);
   return `<div class="feature-card payment-card"><div class="row between"><div><small>${market} payment rule</small><h3>Passenger pays you directly</h3></div>${pill('Direct','warn')}</div><p>After the ride, confirm only when you have actually received payment.</p><button class="${confirmed?'secondary':'primary'} full" data-action="confirm-payment">${confirmed?'✓ Payment marked received':'Confirm payment received'}</button></div>`;
 }
 return `<div class="feature-card payment-card"><div class="row between"><div><small>${market} payment rule</small><h3>Passenger pays Raahi</h3></div>${pill('Raahi','blue')}</div><p>Do not collect the fare from the passenger. Raahi handles collection and driver settlement separately.</p></div>`;
}

function driver(){
 const d=activeDriver();
 const isEngaged=state.engagement?.driverName===d.name && !state.ride;
 const heading=state.ride?.name===d.name?'Your ride is confirmed':isEngaged?'One request is reserved for you':'You’re available';
 return `<div class="screen"><header class="hero-header driver-hero"><div class="brand-row"><div class="brand-mark">R</div><span>Raahi Driver</span>${pill('5 demo drivers')}</div><div class="row between greeting"><div><small>${d.name}</small><h1>${state.driverOnline?heading:'You’re offline'}</h1></div><button class="toggle ${state.driverOnline?'on':''}" data-action="toggle-online"><span></span></button></div></header><div class="content-stack overlap"><div class="feature-card driver-picker"><label><small>Demo driver</small><select id="active-driver">${driverOptions(state.activeDriver)}</select></label><span class="vehicle-tag">${d.type==='toto'?'🛺':'🚗'} ${d.seats} seats</span></div><div class="feature-card driver-location"><div><small>Your current location</small><select id="driver-location">${locationOptions(state.driverLocation)}</select></div><button class="locate square">⌖</button></div>${state.driverOnline?`<div class="row between">${section(isEngaged?'Reserved request':'Driver pool',isEngaged?'Priya is engaged only with you':'Other drivers may be serving other passengers')}${pill(isEngaged?'Engaged':'Online',isEngaged?'warn':'good')}</div>${driverRequestCard(d)}${driverPaymentCard(d)}`:`<div class="empty-state"><span>◌</span><h2>You’re offline</h2><p>Go online when you’re ready to receive nearby ride requests.</p></div>`}</div></div>`;
}

function admin(){
 const policy=state.totoPricing[state.market];
 return `<div class="screen admin-screen"><header class="admin-header"><div><div class="brand-row"><div class="brand-mark">R</div><span>Raahi Admin</span></div><small>Global admin • prototype controls</small></div>${avatar('GA','small')}</header><div class="content-stack"><div class="stats-grid"><div class="stat"><small>Drivers</small><strong>5</strong><span>hard-coded</span></div><div class="stat"><small>Passengers</small><strong>5</strong><span>hard-coded</span></div><div class="stat"><small>Locations</small><strong>3</strong><span>demo points</span></div></div>${section('Local market configuration','Each local admin can apply rules only to their own operating market')}<div class="feature-card admin-config"><label><small>Market</small><select id="admin-market">${['Gomoh','Dhanbad'].map(m=>`<option ${m===state.market?'selected':''}>${m}</option>`).join('')}</select></label></div>
 ${section('ToTo fare by distance','Location-specific slabs; Car remains negotiable')}<div class="feature-card fare-policy-card"><div class="fare-policy-row"><div><strong>Short ride</strong><small>0 to <input id="toto-short-km" type="number" min="0.5" step="0.5" value="${policy.shortKm}"> km</small></div><label><small>Flat fare</small><div class="money-input">₹ <input id="toto-short-fare" type="number" min="10" step="10" value="${policy.shortFare}"></div></label></div><div class="fare-policy-row"><div><strong>Medium ride</strong><small>Over ${policy.shortKm} to <input id="toto-mid-km" type="number" min="1" step="0.5" value="${policy.midKm}"> km</small></div><label><small>Flat fare</small><div class="money-input">₹ <input id="toto-mid-fare" type="number" min="10" step="10" value="${policy.midFare}"></div></label></div><div class="negotiation-threshold"><span>⇄</span><div><strong>More than ${policy.midKm} km</strong><small>Passenger and driver negotiate the fare.</small></div>${pill('Negotiation','warn')}</div></div><div class="rule-preview"><span>ToTo</span><p>In <strong>${state.market}</strong>: up to <strong>${policy.shortKm} km = ₹${policy.shortFare}</strong>, up to <strong>${policy.midKm} km = ₹${policy.midFare}</strong>, then <strong>negotiation</strong>.</p></div>
 ${section('Payment collection','A separate operating rule for each market')}<div class="payment-options"><button class="${state.payment[state.market]==='driver'?'selected':''}" data-paymode="driver"><span class="radio">${state.payment[state.market]==='driver'?'●':'○'}</span><div><strong>Passenger pays driver</strong><small>Driver confirms payment received. Raahi does not collect the fare.</small></div></button><button class="${state.payment[state.market]==='raahi'?'selected':''}" data-paymode="raahi"><span class="radio">${state.payment[state.market]==='raahi'?'●':'○'}</span><div><strong>Passenger pays Raahi</strong><small>Raahi collects the fare and later pays the driver.</small></div></button></div><div class="rule-preview"><span>Payment</span><p>In <strong>${state.market}</strong>, passengers will <strong>${state.payment[state.market]==='driver'?'pay the driver directly':'pay Raahi directly'}</strong>.</p></div>${section('Local admins','Global admin has super access across all markets')}<div class="feature-card admin-list"><div>${avatar('G','tiny')}<span><strong>Gomoh Admin</strong><small>Own fare slabs + payment settings</small></span>${pill('Active','good')}</div><div>${avatar('D','tiny')}<span><strong>Dhanbad Admin</strong><small>Own fare slabs + payment settings</small></span>${pill('Active','good')}</div><button class="secondary full">+ Create local admin</button></div><p class="admin-note">Prototype rule: local admin controls pricing/payment only for their market; global admin can create local admins and override all markets.</p></div></div>`;
}
