function driverRequestCard(d){
 const e=state.engagement;
 const rideAssigned=state.ride?.name===d.name;
 if(rideAssigned){
   const r=state.ride;
   const direct=state.payment[r.market]==='driver';
   if(r.status==='en_route'){
     return `<div class="request-card"><div class="request-top"><div><small>CONFIRMED RIDE</small><h1>₹${r.amount}</h1></div>${pill('On the way','good')}</div><div class="route-summary"><div><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="stem"></div><div><span class="route-dot dark"></span><div><small>Drop</small><strong>${state.to}</strong></div></div></div><div class="request-meta"><span>👤 Priya</span><span>📍 ${d.distance.replace(' away','')} pickup</span><span>${direct?'💵 Passenger pays you':'R Passenger pays Raahi'}</span></div><button class="primary full big" data-action="driver-arrived">I’ve arrived</button></div>`;
   }
   if(r.status==='arrived'){
     return `<div class="request-card"><div class="request-top"><div><small>AT PICKUP</small><h1>Priya</h1></div>${pill('Arrived','good')}</div><div class="route-summary"><div><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="stem"></div><div><span class="route-dot dark"></span><div><small>Destination</small><strong>${state.to}</strong></div></div></div><div class="accepted-box"><span>✓</span><div><strong>You marked Arrived</strong><small>Start only when the passenger is onboard.</small></div></div><button class="primary full big" data-action="start-ride">Start ride</button></div>`;
   }
   if(r.status==='in_progress'){
     return `<div class="request-card"><div class="request-top"><div><small>RIDE IN PROGRESS</small><h1>₹${r.amount}</h1></div>${pill('In ride','blue')}</div><div class="route-summary"><div><span class="route-dot green"></span><div><small>From</small><strong>${state.from}</strong></div></div><div class="stem"></div><div><span class="route-dot dark"></span><div><small>To</small><strong>${state.to}</strong></div></div></div><p>Complete the ride only after reaching the passenger’s destination.</p><button class="primary full big" data-action="complete-ride">Complete ride</button></div>`;
   }
   return `<div class="assigned-banner"><small>RIDE COMPLETE</small><h3>Priya’s ride is completed</h3><p>${state.from} → ${state.to} • Fare ₹${r.amount}</p></div>`;
 }
 if(!e || e.driverName!==d.name){
   return `<div class="empty-state"><span>◌</span><h2>No request for you right now</h2><p>You remain available in the driver pool. Raahi engages only one driver with a passenger at a time.</p></div>`;
 }
 const fixed=isFixedTotoFare();
 const fare=e.amount;
 if(e.status==='counter'){
   return `<div class="request-card"><div class="request-top"><div><small>YOUR COUNTER</small><h1>₹${e.counter}</h1></div>${pill('Waiting for Priya','warn')}</div><div class="route-summary"><div><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="stem"></div><div><span class="route-dot dark"></span><div><small>Drop</small><strong>${state.to}</strong></div></div></div><div class="accepted-box"><span>✓</span><div><strong>Counter sent</strong><small>Priya can accept or decline. No further counter round.</small></div></div></div>`;
 }
 if(e.status==='draft-counter' && !fixed){
   return `<div class="request-card"><div class="request-top"><div><small>PRIYA'S OFFER</small><h1>₹${fare}</h1></div><div class="countdown">24s</div></div><div class="route-summary"><div><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="stem"></div><div><span class="route-dot dark"></span><div><small>Drop</small><strong>${state.to}</strong></div></div></div><div class="request-meta"><span>${d.type==='toto'?'🛺':'🚗'} ${rideLabel()}</span><span>👤 Priya</span><span>📍 ${d.distance.replace(' away','')} pickup</span></div><div class="counter-box"><small>Your one counter</small><div><button data-counter="-10">−</button><strong>₹${state.counterDraft}</strong><button data-counter="10">+</button></div><button class="primary full" data-action="send-counter">Send ₹${state.counterDraft} counter</button><button class="text-button" data-action="driver-pass">Pass this request</button></div></div>`;
 }
 if(fixed){
   const rule=totoFareRule();
   return `<div class="request-card"><div class="request-top"><div><small>FIXED LOCAL FARE</small><h1>₹${fare}</h1></div>${pill(rule.distance+' km','blue')}</div><div class="route-summary"><div><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="stem"></div><div><span class="route-dot dark"></span><div><small>Drop</small><strong>${state.to}</strong></div></div></div><div class="request-meta"><span>🛺 ToTo</span><span>👤 Priya</span><span>📍 ${d.distance.replace(' away','')} pickup</span></div><div class="fixed-driver-rule"><strong>${e.market} fixed this fare.</strong><small>You can Accept or Pass. Counterquotes are disabled.</small></div><div class="two-buttons"><button class="secondary" data-action="driver-pass">Pass</button><button class="primary" data-action="accept-driver">Accept ₹${fare}</button></div></div>`;
 }
 return `<div class="request-card"><div class="request-top"><div><small>PRIYA'S OFFER</small><h1>₹${fare}</h1></div><div class="countdown">24s</div></div><div class="route-summary"><div><span class="route-dot green"></span><div><small>Pickup</small><strong>${state.from}</strong></div></div><div class="stem"></div><div><span class="route-dot dark"></span><div><small>Drop</small><strong>${state.to}</strong></div></div></div><div class="request-meta"><span>${d.type==='toto'?'🛺':'🚗'} ${rideLabel()}</span><span>👤 Priya</span><span>📍 ${d.distance.replace(' away','')} pickup</span></div><div class="two-buttons"><button class="secondary" data-action="counter-mode">Counter once</button><button class="primary" data-action="accept-driver">Accept ₹${fare}</button></div><button class="text-button" data-action="driver-pass">Pass this request</button></div>`;
}

function driverPaymentCard(d){
 if(state.ride?.name!==d.name || state.ride.status!=='completed') return '';
 const market=state.ride.market;
 const direct=state.payment[market]==='driver';
 if(direct){
   const confirmed=Boolean(state.paymentConfirmed[d.name]);
   return `<div class="feature-card payment-card"><div class="row between"><div><small>${market} payment rule</small><h3>${confirmed?'Payment received':'Passenger pays you directly'}</h3></div>${pill(confirmed?'Confirmed':'Direct',confirmed?'good':'warn')}</div><p>${confirmed?`You confirmed receiving ₹${state.ride.amount}.`:`Confirm only after you actually receive ₹${state.ride.amount} from Priya.`}</p><button class="${confirmed?'secondary':'primary'} full" data-action="confirm-payment" ${confirmed?'disabled':''}>${confirmed?'✓ Payment marked received':'Confirm payment received'}</button></div>`;
 }
 const paid=Boolean(state.raahiPaymentPaid[d.name]);
 return `<div class="feature-card payment-card"><div class="row between"><div><small>${market} payment rule</small><h3>Passenger pays Raahi</h3></div>${pill(paid?'Passenger paid':'Raahi','blue')}</div><p>${paid?'Raahi has recorded the passenger payment. Driver settlement remains separate.':'Do not collect the fare from Priya. Raahi handles collection and settlement separately.'}</p></div>`;
}

function driver(){
 const d=activeDriver();
 const isEngaged=state.engagement?.driverName===d.name && !state.ride;
 const assignedRide=state.ride?.name===d.name ? state.ride : null;
 const locked=isEngaged || (assignedRide && assignedRide.status!=='completed');
 const heading=assignedRide
   ? assignedRide.status==='en_route'?'Go to pickup':assignedRide.status==='arrived'?'Passenger pickup':assignedRide.status==='in_progress'?'Ride in progress':'Ride completed'
   : isEngaged?'One request is reserved for you':'You’re available';
 return `<div class="screen"><header class="hero-header driver-hero"><div class="brand-row"><div class="brand-mark">R</div><span>Raahi Driver</span>${pill('5 demo drivers')}</div><div class="row between greeting"><div><small>${d.name}</small><h1>${state.driverOnline?heading:'You’re offline'}</h1></div><button class="toggle ${state.driverOnline?'on':''}" data-action="toggle-online" ${locked?'disabled':''}><span></span></button></div></header><div class="content-stack overlap"><div class="feature-card driver-picker"><label><small>Demo driver</small><select id="active-driver">${driverOptions(state.activeDriver)}</select></label><span class="vehicle-tag">${d.type==='toto'?'🛺':'🚗'} ${d.seats} seats</span></div><div class="feature-card driver-location"><div><small>Your current location</small><select id="driver-location">${locationOptions(state.driverLocation)}</select></div><button class="locate square" disabled>⌖</button></div>${state.driverOnline?`<div class="row between">${section(isEngaged?'Reserved request':assignedRide?'Current ride':'Driver pool',isEngaged?'Priya is engaged only with you':assignedRide?'Passenger and driver share this same ride state':'Waiting for a nearby eligible request')}${pill(isEngaged?'Engaged':assignedRide?.status==='completed'?'Available':'Online',isEngaged?'warn':'good')}</div>${driverRequestCard(d)}${driverPaymentCard(d)}`:`<div class="empty-state"><span>◌</span><h2>You’re offline</h2><p>Go online when you’re ready to receive nearby ride requests.</p></div>`}</div></div>`;
}

function admin(){
 const market=adminMarket();
 const policy=state.totoPricing[market];
 const prox=state.proximity[market];
 const isGlobal=state.adminPersona==='global';
 const stats=market==='Gomoh'?{waiting:3,drivers:4,rides:1,wait:'4 min'}:{waiting:5,drivers:3,rides:2,wait:'7 min'};
 const personaLabel=isGlobal?'Global Admin':`${market} Local Admin`;
 return `<div class="screen admin-screen"><header class="admin-header"><div><div class="brand-row"><div class="brand-mark">R</div><span>Raahi Admin</span></div><small>${personaLabel}</small></div>${avatar(isGlobal?'GA':market[0]+'A','small')}</header><div class="content-stack">
 <div class="feature-card admin-config"><label><small>Prototype admin</small><select id="admin-persona"><option value="global" ${state.adminPersona==='global'?'selected':''}>Global Admin</option><option value="gomoh" ${state.adminPersona==='gomoh'?'selected':''}>Gomoh Local Admin</option><option value="dhanbad" ${state.adminPersona==='dhanbad'?'selected':''}>Dhanbad Local Admin</option></select></label>${isGlobal?`<label><small>Open market</small><select id="admin-market">${['Gomoh','Dhanbad'].map(m=>`<option ${m===state.market?'selected':''}>${m}</option>`).join('')}</select></label>`:`<div class="admin-note">Your scope is locked to <strong>${market}</strong>.</div>`}</div>
 ${state.adminNotice?`<div class="assigned-banner"><small>ADMIN ACTION</small><h3>${state.adminNotice}</h3></div>`:''}
 <div class="stats-grid"><div class="stat"><small>Waiting</small><strong>${stats.waiting}</strong><span>passengers</span></div><div class="stat"><small>Available</small><strong>${stats.drivers}</strong><span>drivers</span></div><div class="stat"><small>Active rides</small><strong>${stats.rides}</strong><span>now</span></div></div><div class="feature-card"><div class="row between"><div><small>Oldest wait</small><h3>${stats.wait}</h3></div>${pill('Operational view','blue')}</div><p>Admin observes supply and demand; Raahi still owns matching.</p></div>
 ${section('Market status','Pause new demand without disrupting existing rides')}<div class="feature-card"><div class="row between"><div><small>${market}</small><h3>${state.marketStatus[market]==='active'?'Accepting new requests':'New requests paused'}</h3></div>${pill(state.marketStatus[market]==='active'?'Active':'Paused',state.marketStatus[market]==='active'?'good':'warn')}</div><button class="${state.marketStatus[market]==='active'?'secondary':'primary'} full" data-action="${state.marketStatus[market]==='active'?'pause-market':'resume-market'}">${state.marketStatus[market]==='active'?'Pause new requests':'Resume market'}</button></div>
 ${section('Vehicle availability','Applies to new requests only')}<div class="payment-options"><button class="${state.vehicleEnabled[market].toto?'selected':''}" data-vehicle-toggle="toto"><span class="radio">${state.vehicleEnabled[market].toto?'●':'○'}</span><div><strong>ToTo</strong><small>${state.vehicleEnabled[market].toto?'Enabled':'Disabled'} in ${market}</small></div></button><button class="${state.vehicleEnabled[market].car?'selected':''}" data-vehicle-toggle="car"><span class="radio">${state.vehicleEnabled[market].car?'●':'○'}</span><div><strong>Car</strong><small>${state.vehicleEnabled[market].car?'Enabled':'Disabled'} in ${market}</small></div></button></div>
 ${section('ToTo fare by distance','Fixed slabs first; negotiation beyond the last threshold')}<div class="feature-card fare-policy-card"><div class="fare-policy-row"><div><strong>Short ride</strong><small>0 to <input id="toto-short-km" type="number" min="0.5" step="0.5" value="${policy.shortKm}"> km</small></div><label><small>Flat fare</small><div class="money-input">₹ <input id="toto-short-fare" type="number" min="10" step="10" value="${policy.shortFare}"></div></label></div><div class="fare-policy-row"><div><strong>Medium ride</strong><small>Over ${policy.shortKm} to <input id="toto-mid-km" type="number" min="1" step="0.5" value="${policy.midKm}"> km</small></div><label><small>Flat fare</small><div class="money-input">₹ <input id="toto-mid-fare" type="number" min="10" step="10" value="${policy.midFare}"></div></label></div><div class="negotiation-threshold"><span>⇄</span><div><strong>More than ${policy.midKm} km</strong><small>Passenger and driver negotiate once.</small></div>${pill('Negotiation','warn')}</div></div><div class="rule-preview"><span>ToTo</span><p>Up to <strong>${policy.shortKm} km = ₹${policy.shortFare}</strong>, up to <strong>${policy.midKm} km = ₹${policy.midFare}</strong>, then <strong>negotiation</strong>.</p></div>
 ${section('Payment collection','One rule for all new rides originating in this market')}<div class="payment-options"><button class="${state.payment[market]==='driver'?'selected':''}" data-paymode="driver"><span class="radio">${state.payment[market]==='driver'?'●':'○'}</span><div><strong>Passenger pays driver</strong><small>Driver confirms receipt after ride.</small></div></button><button class="${state.payment[market]==='raahi'?'selected':''}" data-paymode="raahi"><span class="radio">${state.payment[market]==='raahi'?'●':'○'}</span><div><strong>Passenger pays Raahi</strong><small>Driver does not collect passenger fare.</small></div></button></div>
 ${section('Nearby-driver search','FIFO applies inside the current search radius')}<div class="feature-card fare-policy-card"><div class="fare-policy-row"><div><strong>ToTo</strong><small>First → Expand → Maximum</small></div><label><small>km</small><div class="money-input"><input data-prox-vehicle="toto" data-prox-index="0" type="number" min="1" step="1" value="${prox.toto[0]}"> / <input data-prox-vehicle="toto" data-prox-index="1" type="number" min="1" step="1" value="${prox.toto[1]}"> / <input data-prox-vehicle="toto" data-prox-index="2" type="number" min="1" step="1" value="${prox.toto[2]}"></div></label></div><div class="fare-policy-row"><div><strong>Car</strong><small>First → Expand → Maximum</small></div><label><small>km</small><div class="money-input"><input data-prox-vehicle="car" data-prox-index="0" type="number" min="1" step="1" value="${prox.car[0]}"> / <input data-prox-vehicle="car" data-prox-index="1" type="number" min="1" step="1" value="${prox.car[1]}"> / <input data-prox-vehicle="car" data-prox-index="2" type="number" min="1" step="1" value="${prox.car[2]}"></div></label></div></div><div class="rule-preview"><span>Matching</span><p>Raahi first finds compatible drivers within the current radius, then oldest FIFO priority wins.</p></div>
 ${section('Driver authorization','Permission to serve this market; not queue priority')}<div class="feature-card admin-list">${drivers.map(d=>{const ok=state.driverAuth[market][d.name];return `<div>${avatar(d.name,'tiny')}<span><strong>${d.name}</strong><small>${d.vehicle}</small></span>${pill(ok?'Authorized':'Not authorized',ok?'good':'warn')}<button class="${ok?'secondary':'primary'}" data-driver-auth="${d.name}">${ok?'Suspend':'Authorize'}</button></div>`}).join('')}</div>
 <button class="primary full big" data-action="publish-admin">Publish ${market} changes</button><p class="fineprint">Prototype changes are already reflected in-memory; Publish represents the final product’s explicit policy publication step.</p>
 ${isGlobal?`${section('Local admins','Global governance only')}<div class="feature-card admin-list"><div>${avatar('G','tiny')}<span><strong>Gomoh Admin</strong><small>Scoped to Gomoh</small></span>${pill('Active','good')}</div><div>${avatar('D','tiny')}<span><strong>Dhanbad Admin</strong><small>Scoped to Dhanbad</small></span>${pill('Active','good')}</div><button class="secondary full" data-action="create-local-admin">+ Create local admin</button></div>`:`<p class="admin-note">As a Local Admin you cannot switch markets, reorder FIFO, or manually assign passengers to drivers.</p>`}
 </div></div>`;
}
